
; Generated by script 'bttest'
; (load "btable.scm")  ; EDIT HERE: load the implementation under test
(define t1 (make-table numcmp))  ; EDIT HERE: the constructor
(define t2 (make-table numcmp))  ; EDIT HERE: the constructor
(define (numcmp a b) (- a b))
(define (strcmp a b) (cond ((string<? a b) -1) ((string>? a b) +1) (else 0)))

(insert!  t2     216     "cord" )                            ;klist length= 5 
(insert!  t1     141     'pig )                              ;klist length= 2 
(insert!  t2     337     'cat )                              ;klist length= 3 
(insert!  t1     339     '(romeo juliet) )                   ;klist length= 1 
(insert!  t2     207     '() )                               ;klist length= 3 
(insert!  t2     299     "twine" )                           ;klist length= 1 
(insert!  t2     404     'owl )                              ;klist length= 3 
(insert!  t2     107     'fox )                              ;klist length= 2 
(insert!  t2     353     assoc )                             ;klist length= 2 
(insert!  t2     175     'pig )                              ;klist length= 3 
(insert!  t1     360     #t )                                ;klist length= 2 
(insert!  t2     260     '(romeo juliet) )                   ;klist length= 1 
(insert!  t2     304     1.7321 )                            ;klist length= 5 
(insert!  t2     335     '(1 . 2) )                          ;klist length= 3 
(insert!  t1     205     'cat )                              ;klist length= 1 
(insert!  t1     152     'cow )                              ;klist length= 4 
(insert!  t1     437     7 )                                 ;klist length= 3 
(insert!  t1     447     1.7321 )                            ;klist length= 3 
(insert!  t1     194     cdr )                               ;klist length= 1 
(insert!  t2     342     3 )                                 ;klist length= 4 
(insert!  t1     128     #t )                                ;klist length= 2 
(insert!  t1     304     "rope" )                            ;klist length= 1 
(insert!  t2     211     'pig )                              ;klist length= 3 
(insert!  t1     160     '() )                               ;klist length= 3 
(insert!  t2     276     'fox )                              ;klist length= 2 
(insert!  t1     264     2 )                                 ;klist length= 3 
(insert!  t1     201     "yarn" )                            ;klist length= 5 
(insert!  t1     267     "rope" )                            ;klist length= 4 
(insert!  t2     130     #t )                                ;klist length= 4 
(insert!  t1     388     '(romeo juliet) )                   ;klist length= 2 
(insert!  t2     233     2 )                                 ;klist length= 3 
(insert!  t2     198     '(larry moe curly) )                ;klist length= 4 
(insert!  t2     421     "yarn" )                            ;klist length= 1 
(insert!  t2     436     7 )                                 ;klist length= 2 
(insert!  t2     213     4 )                                 ;klist length= 5 
(insert!  t2     271     assoc )                             ;klist length= 1 
(insert!  t2     183     2 )                                 ;klist length= 5 
(insert!  t1     105     "cord" )                            ;klist length= 2 
(insert!  t1     191     '(romeo juliet) )                   ;klist length= 4 
(insert!  t2     302     '(larry moe curly) )                ;klist length= 5 
(insert!  t2     283     '(a . b) )                          ;klist length= 5 
(insert!  t2     108     2.2361 )                            ;klist length= 2 
(insert!  t2     276     1.618 )                             ;klist length= 3 
(insert!  t1     406     1.618 )                             ;klist length= 2 
(insert!  t1     253     assoc )                             ;klist length= 2 
(insert!  t1     142     'cow )                              ;klist length= 4 
(insert!  t2     148     3 )                                 ;klist length= 2 
(insert!  t2     392     #t )                                ;klist length= 5 
(insert!  t2     113     '(1 . 2) )                          ;klist length= 4 
(insert!  t2     195     1.618 )                             ;klist length= 3 
(insert!  t1     409     assoc )                             ;klist length= 3 
(insert!  t1     139     'pig )                              ;klist length= 5 
(insert!  t2     190     1.618 )                             ;klist length= 2 
(insert!  t1     296     "rope" )                            ;klist length= 5 
(insert!  t1     231     1.7321 )                            ;klist length= 5 
(insert!  t2     169     '(romeo juliet) )                   ;klist length= 4 
(insert!  t2     392     car )                               ;klist length= 4 
(insert!  t1     137     1.4142 )                            ;klist length= 1 
(insert!  t2     241     4 )                                 ;klist length= 1 
(insert!  t2     151     '(one) )                            ;klist length= 5 
(insert!  t2     361     3 )                                 ;klist length= 2 
(insert!  t1     361     2.2361 )                            ;klist length= 5 
(insert!  t1     135     list )                              ;klist length= 5 
(insert!  t2     441     list )                              ;klist length= 1 
(insert!  t2     447     1.4142 )                            ;klist length= 1 
(insert!  t1     404     'fox )                              ;klist length= 5 
(insert!  t2     250     cdr )                               ;klist length= 2 
(insert!  t1     410     1 )                                 ;klist length= 4 
(insert!  t2     372     "cord" )                            ;klist length= 2 
(insert!  t2     394     'dog )                              ;klist length= 1 
(insert!  t1     290     cdr )                               ;klist length= 4 
(insert!  t1     280     cdr )                               ;klist length= 2 
(insert!  t1     412     1.618 )                             ;klist length= 4 
(insert!  t1     220     '(1 . 2) )                          ;klist length= 2 
(insert!  t2     197     1 )                                 ;klist length= 2 
(insert!  t2     171     "yarn" )                            ;klist length= 5 
(insert!  t1     369     car )                               ;klist length= 1 
(insert!  t2     262     'pig )                              ;klist length= 4 
(insert!  t2     130     3.1416 )                            ;klist length= 3 
(insert!  t1     285     '() )                               ;klist length= 2 
(insert!  t2     324     3 )                                 ;klist length= 2 
(insert!  t1     171     assoc )                             ;klist length= 2 
(insert!  t2     329     "cord" )                            ;klist length= 5 
(insert!  t1     167     2.2361 )                            ;klist length= 3 
(insert!  t2     397     '(larry moe curly) )                ;klist length= 4 
(insert!  t1     131     '(one) )                            ;klist length= 1 
(insert!  t1     167     car )                               ;klist length= 5 
(insert!  t2     242     'cow )                              ;klist length= 2 
(insert!  t2     274     'jay )                              ;klist length= 1 
(insert!  t1     428     '(a . b) )                          ;klist length= 3 
(insert!  t1     400     6 )                                 ;klist length= 2 
(insert!  t1     316     '(one) )                            ;klist length= 2 
(insert!  t2     175     3.1416 )                            ;klist length= 5 
(insert!  t1     376     '(one) )                            ;klist length= 5 
(insert!  t1     438     6 )                                 ;klist length= 4 
(insert!  t1     363     'jay )                              ;klist length= 5 
(insert!  t1     318     '(larry moe curly) )                ;klist length= 5 
(insert!  t2     175     3.1416 )                            ;klist length= 4 
(insert!  t2     362     3 )                                 ;klist length= 4 
(insert!  t1     262     "cord" )                            ;klist length= 4 
(insert!  t2     194     "rope" )                            ;klist length= 2 
(insert!  t1     438     '(romeo juliet) )                   ;klist length= 3 
(insert!  t1     399     '(1 . 2) )                          ;klist length= 1 
(insert!  t1     417     1.618 )                             ;klist length= 2 
(insert!  t1     375     '(one) )                            ;klist length= 1 
(insert!  t1     389     'cat )                              ;klist length= 1 
(insert!  t1     375     1.4142 )                            ;klist length= 4 
(insert!  t1     169     cdr )                               ;klist length= 4 
(insert!  t1     216     assoc )                             ;klist length= 5 
(insert!  t1     236     1.4142 )                            ;klist length= 2 
(insert!  t2     191     2 )                                 ;klist length= 5 
(insert!  t1     344     '(1 . 2) )                          ;klist length= 1 
(insert!  t2     402     "rope" )                            ;klist length= 5 
(insert!  t1     126     6 )                                 ;klist length= 3 
(insert!  t1     257     'jay )                              ;klist length= 1 
(insert!  t1     142     1.7321 )                            ;klist length= 1 
(insert!  t2     442     'eel )                              ;klist length= 3 
(insert!  t2     257     2.2361 )                            ;klist length= 2 
(insert!  t1     110     4 )                                 ;klist length= 5 
(insert!  t1     199     assoc )                             ;klist length= 4 
(insert!  t1     390     1.4142 )                            ;klist length= 4 
(insert!  t2     335     #f )                                ;klist length= 1 
(insert!  t2     247     "twine" )                           ;klist length= 2 
(insert!  t1     310     #f )                                ;klist length= 5 
(insert!  t2     226     car )                               ;klist length= 4 
(insert!  t2     314     'cat )                              ;klist length= 2 
(insert!  t1     122     1.4142 )                            ;klist length= 1 
(insert!  t2     297     #t )                                ;klist length= 2 
(insert!  t2     424     5 )                                 ;klist length= 3 
(insert!  t1     445     'jay )                              ;klist length= 5 
(insert!  t2     198     'dog )                              ;klist length= 2 
(insert!  t2     330     '(romeo juliet) )                   ;klist length= 2 
(insert!  t1     400     3.1416 )                            ;klist length= 2 
(insert!  t1     178     4 )                                 ;klist length= 1 
(insert!  t2     185     7 )                                 ;klist length= 2 
(insert!  t1     386     'cow )                              ;klist length= 1 
(insert!  t1     414     '(larry moe curly) )                ;klist length= 1 
(insert!  t1     409     list )                              ;klist length= 5 
(insert!  t2     406     '() )                               ;klist length= 2 
(insert!  t2     358     1.618 )                             ;klist length= 2 
(insert!  t2     119     "rope" )                            ;klist length= 3 
(insert!  t1     437     list )                              ;klist length= 3 
(insert!  t2     223     '(romeo juliet) )                   ;klist length= 5 
(insert!  t1     334     "cord" )                            ;klist length= 2 
(insert!  t1     448     '(1 . 2) )                          ;klist length= 3 
(insert!  t1     317     car )                               ;klist length= 4 
(insert!  t2     170     #f )                                ;klist length= 4 
(insert!  t2     369     '(a . b) )                          ;klist length= 4 
(insert!  t2     293     'dog )                              ;klist length= 4 
(insert!  t2     416     2 )                                 ;klist length= 2 
(insert!  t2     419     "twine" )                           ;klist length= 2 
(insert!  t2     128     cdr )                               ;klist length= 4 
(insert!  t2     212     '(a . b) )                          ;klist length= 5 
(insert!  t1     345     1.4142 )                            ;klist length= 3 
(insert!  t2     179     4 )                                 ;klist length= 3 
(insert!  t2     398     "rope" )                            ;klist length= 3 
(insert!  t2     382     3 )                                 ;klist length= 2 
(insert!  t2     414     #t )                                ;klist length= 3 
(insert!  t2     400     'owl )                              ;klist length= 4 
(insert!  t2     285     "twine" )                           ;klist length= 2 
(insert!  t2     277     '(larry moe curly) )                ;klist length= 1 
(insert!  t2     244     3 )                                 ;klist length= 4 
(insert!  t2     401     'eel )                              ;klist length= 2 
(insert!  t1     298     '(1 . 2) )                          ;klist length= 4 
(insert!  t2     416     '(a . b) )                          ;klist length= 3 
(insert!  t2     379     cdr )                               ;klist length= 5 
(insert!  t2     384     3 )                                 ;klist length= 1 
(insert!  t1     446     '(1 . 2) )                          ;klist length= 2 
(insert!  t2     420     #f )                                ;klist length= 3 
(insert!  t1     422     'owl )                              ;klist length= 3 
(insert!  t2     189     assoc )                             ;klist length= 5 
(insert!  t1     207     5 )                                 ;klist length= 3 
(insert!  t2     265     'dog )                              ;klist length= 3 
(insert!  t1     180     3.1416 )                            ;klist length= 1 
(insert!  t1     283     car )                               ;klist length= 5 
(insert!  t2     389     5 )                                 ;klist length= 5 
(insert!  t2     368     'cow )                              ;klist length= 1 
(insert!  t1     308     2 )                                 ;klist length= 1 
(insert!  t1     333     "rope" )                            ;klist length= 5 
(insert!  t1     335     1.4142 )                            ;klist length= 5 
(insert!  t1     297     1.7321 )                            ;klist length= 2 
(insert!  t2     390     '(one) )                            ;klist length= 5 
(insert!  t2     260     4 )                                 ;klist length= 5 
(insert!  t1     125     'fox )                              ;klist length= 2 
(insert!  t1     201     '(one) )                            ;klist length= 1 
(insert!  t2     281     'pig )                              ;klist length= 4 
(insert!  t2     186     car )                               ;klist length= 1 
(insert!  t1     393     'fox )                              ;klist length= 3 
(insert!  t1     189     '(one) )                            ;klist length= 3 
(insert!  t1     265     "rope" )                            ;klist length= 3 
(insert!  t1     174     2.2361 )                            ;klist length= 1 
(insert!  t1     435     2 )                                 ;klist length= 3 
(insert!  t2     232     cdr )                               ;klist length= 5 
(insert!  t1     401     3.1416 )                            ;klist length= 1 
(insert!  t1     349     '(romeo juliet) )                   ;klist length= 2 
(insert!  t2     280     6 )                                 ;klist length= 5 
(insert!  t1     274     "yarn" )                            ;klist length= 2 
(insert!  t2     337     "twine" )                           ;klist length= 3 
(insert!  t2     244     'pig )                              ;klist length= 2 
(insert!  t2     284     'dog )                              ;klist length= 3 
(if (equal? "twine"  (lookup  t2    247   )   ) 'match (error "Error: Mismatch:" 1))
(if (equal? 'owl  (lookup  t1    422   )   ) 'match (error "Error: Mismatch:" 2))
(if (equal? 1.618  (lookup  t2    276   )   ) 'match (error "Error: Mismatch:" 3))
(if (equal? #f (lookup  t2    413   )   ) 'match (error "Error: Mismatch:" 4))
(if (equal? cdr  (lookup  t1    290   )   ) 'match (error "Error: Mismatch:" 5))
(if (equal? #f (lookup  t1    279   )   ) 'match (error "Error: Mismatch:" 6))
(if (equal? "yarn"  (lookup  t1    274   )   ) 'match (error "Error: Mismatch:" 7))
(if (equal? #f (lookup  t1    181   )   ) 'match (error "Error: Mismatch:" 8))
(if (equal? 3.1416  (lookup  t1    401   )   ) 'match (error "Error: Mismatch:" 9))
(if (equal? 2.2361  (lookup  t2    257   )   ) 'match (error "Error: Mismatch:" 10))
(if (equal? "cord"  (lookup  t2    216   )   ) 'match (error "Error: Mismatch:" 11))
(if (equal? #f (lookup  t2    219   )   ) 'match (error "Error: Mismatch:" 12))
(if (equal? #f (lookup  t1    440   )   ) 'match (error "Error: Mismatch:" 13))
(if (equal? 3.1416  (lookup  t2    175   )   ) 'match (error "Error: Mismatch:" 14))
(if (equal? #f (lookup  t1    343   )   ) 'match (error "Error: Mismatch:" 15))
(if (equal? 2  (lookup  t2    183   )   ) 'match (error "Error: Mismatch:" 16))
(if (equal? 'dog  (lookup  t2    198   )   ) 'match (error "Error: Mismatch:" 17))
(if (equal? 3.1416  (lookup  t2    175   )   ) 'match (error "Error: Mismatch:" 18))
(if (equal? '(romeo juliet)  (lookup  t1    191   )   ) 'match (error "Error: Mismatch:" 19))
(if (equal? #f (lookup  t2    327   )   ) 'match (error "Error: Mismatch:" 20))
(if (equal? #f (lookup  t2    307   )   ) 'match (error "Error: Mismatch:" 21))
(if (equal? 'fox  (lookup  t1    125   )   ) 'match (error "Error: Mismatch:" 22))
(if (equal? '(1 . 2)  (lookup  t1    298   )   ) 'match (error "Error: Mismatch:" 23))
(if (equal? 3.1416  (lookup  t1    180   )   ) 'match (error "Error: Mismatch:" 24))
(if (equal? 'jay  (lookup  t1    445   )   ) 'match (error "Error: Mismatch:" 25))
(if (equal? 'jay  (lookup  t1    363   )   ) 'match (error "Error: Mismatch:" 26))
(if (equal? #f  (lookup  t2    335   )   ) 'match (error "Error: Mismatch:" 27))
(if (equal? "yarn"  (lookup  t2    171   )   ) 'match (error "Error: Mismatch:" 28))
(if (equal? #f (lookup  t1    146   )   ) 'match (error "Error: Mismatch:" 29))
(if (equal? cdr  (lookup  t2    250   )   ) 'match (error "Error: Mismatch:" 30))
(if (equal? 3.1416  (lookup  t1    401   )   ) 'match (error "Error: Mismatch:" 31))
(if (equal? 1.618  (lookup  t2    195   )   ) 'match (error "Error: Mismatch:" 32))
(if (equal? #f (lookup  t1    293   )   ) 'match (error "Error: Mismatch:" 33))
(if (equal? #f (lookup  t2    407   )   ) 'match (error "Error: Mismatch:" 34))
(if (equal? #f (lookup  t1    219   )   ) 'match (error "Error: Mismatch:" 35))
(if (equal? 3.1416  (lookup  t1    400   )   ) 'match (error "Error: Mismatch:" 36))
(if (equal? #f (lookup  t1    192   )   ) 'match (error "Error: Mismatch:" 37))
(if (equal? #f (lookup  t2    303   )   ) 'match (error "Error: Mismatch:" 38))
(if (equal? list  (lookup  t1    409   )   ) 'match (error "Error: Mismatch:" 39))
(if (equal? assoc  (lookup  t2    353   )   ) 'match (error "Error: Mismatch:" 40))
(if (equal? #f (lookup  t1    124   )   ) 'match (error "Error: Mismatch:" 41))
(if (equal? #f (lookup  t1    293   )   ) 'match (error "Error: Mismatch:" 42))
(if (equal? 3  (lookup  t2    324   )   ) 'match (error "Error: Mismatch:" 43))
(if (equal? #f (lookup  t1    188   )   ) 'match (error "Error: Mismatch:" 44))
(if (equal? #f (lookup  t2    432   )   ) 'match (error "Error: Mismatch:" 45))
(if (equal? #f  (lookup  t2    420   )   ) 'match (error "Error: Mismatch:" 46))
(if (equal? '(larry moe curly)  (lookup  t1    414   )   ) 'match (error "Error: Mismatch:" 47))
(if (equal? #f (lookup  t2    300   )   ) 'match (error "Error: Mismatch:" 48))
(if (equal? 4  (lookup  t2    260   )   ) 'match (error "Error: Mismatch:" 49))
(if (equal? 4  (lookup  t2    179   )   ) 'match (error "Error: Mismatch:" 50))
(if (equal? #f (lookup  t2    272   )   ) 'match (error "Error: Mismatch:" 51))
(if (equal? 1.7321  (lookup  t1    142   )   ) 'match (error "Error: Mismatch:" 52))
(if (equal? 1.4142  (lookup  t1    375   )   ) 'match (error "Error: Mismatch:" 53))
(if (equal? #f (lookup  t2    370   )   ) 'match (error "Error: Mismatch:" 54))
(if (equal? #f (lookup  t1    261   )   ) 'match (error "Error: Mismatch:" 55))
(if (equal? #f (lookup  t2    255   )   ) 'match (error "Error: Mismatch:" 56))
(if (equal? 'eel  (lookup  t2    401   )   ) 'match (error "Error: Mismatch:" 57))
(if (equal? 1.618  (lookup  t2    190   )   ) 'match (error "Error: Mismatch:" 58))
(if (equal? '(romeo juliet)  (lookup  t2    169   )   ) 'match (error "Error: Mismatch:" 59))
(if (equal? #f (lookup  t2    152   )   ) 'match (error "Error: Mismatch:" 60))
(if (equal? '(romeo juliet)  (lookup  t1    349   )   ) 'match (error "Error: Mismatch:" 61))
(if (equal? "rope"  (lookup  t1    296   )   ) 'match (error "Error: Mismatch:" 62))
(if (equal? '(one)  (lookup  t1    201   )   ) 'match (error "Error: Mismatch:" 63))
(if (equal? 'cow  (lookup  t2    368   )   ) 'match (error "Error: Mismatch:" 64))
(if (equal? 1  (lookup  t2    197   )   ) 'match (error "Error: Mismatch:" 65))
(if (equal? #f (lookup  t2    364   )   ) 'match (error "Error: Mismatch:" 66))
(if (equal? '(a . b)  (lookup  t2    369   )   ) 'match (error "Error: Mismatch:" 67))
(if (equal? "yarn"  (lookup  t2    421   )   ) 'match (error "Error: Mismatch:" 68))
(if (equal? #f (lookup  t1    210   )   ) 'match (error "Error: Mismatch:" 69))
(if (equal? '()  (lookup  t1    285   )   ) 'match (error "Error: Mismatch:" 70))
(if (equal? '(a . b)  (lookup  t2    212   )   ) 'match (error "Error: Mismatch:" 71))
(if (equal? #f (lookup  t1    348   )   ) 'match (error "Error: Mismatch:" 72))
(if (equal? #f (lookup  t2    375   )   ) 'match (error "Error: Mismatch:" 73))
(if (equal? #f (lookup  t1    212   )   ) 'match (error "Error: Mismatch:" 74))
(if (equal? #f (lookup  t1    295   )   ) 'match (error "Error: Mismatch:" 75))
(if (equal? 4  (lookup  t2    260   )   ) 'match (error "Error: Mismatch:" 76))
(if (equal? '(one)  (lookup  t1    131   )   ) 'match (error "Error: Mismatch:" 77))
(if (equal? #f (lookup  t1    132   )   ) 'match (error "Error: Mismatch:" 78))
(if (equal? 1  (lookup  t2    197   )   ) 'match (error "Error: Mismatch:" 79))
(if (equal? "rope"  (lookup  t1    304   )   ) 'match (error "Error: Mismatch:" 80))
(if (equal? #f  (lookup  t1    310   )   ) 'match (error "Error: Mismatch:" 81))
(if (equal? 2  (lookup  t2    233   )   ) 'match (error "Error: Mismatch:" 82))
(if (equal? #f (lookup  t2    123   )   ) 'match (error "Error: Mismatch:" 83))
(if (equal? "twine"  (lookup  t2    337   )   ) 'match (error "Error: Mismatch:" 84))
(if (equal? car  (lookup  t1    167   )   ) 'match (error "Error: Mismatch:" 85))
(if (equal? '(romeo juliet)  (lookup  t1    339   )   ) 'match (error "Error: Mismatch:" 86))
(if (equal? '()  (lookup  t1    160   )   ) 'match (error "Error: Mismatch:" 87))
(if (equal? #f (lookup  t1    150   )   ) 'match (error "Error: Mismatch:" 88))
(if (equal? #f (lookup  t2    117   )   ) 'match (error "Error: Mismatch:" 89))
(if (equal? 2  (lookup  t1    264   )   ) 'match (error "Error: Mismatch:" 90))
(if (equal? #f (lookup  t1    356   )   ) 'match (error "Error: Mismatch:" 91))
(if (equal? car  (lookup  t2    392   )   ) 'match (error "Error: Mismatch:" 92))
(if (equal? 2  (lookup  t1    435   )   ) 'match (error "Error: Mismatch:" 93))
(if (equal? "cord"  (lookup  t1    334   )   ) 'match (error "Error: Mismatch:" 94))
(if (equal? #f (lookup  t1    134   )   ) 'match (error "Error: Mismatch:" 95))
(if (equal? #f (lookup  t2    131   )   ) 'match (error "Error: Mismatch:" 96))
(if (equal? 2.2361  (lookup  t1    174   )   ) 'match (error "Error: Mismatch:" 97))
(if (equal? 1.4142  (lookup  t1    375   )   ) 'match (error "Error: Mismatch:" 98))
(if (equal? #f (lookup  t1    101   )   ) 'match (error "Error: Mismatch:" 99))
(if (equal? #f (lookup  t2    312   )   ) 'match (error "Error: Mismatch:" 100))
(if (equal? cdr  (lookup  t2    250   )   ) 'match (error "Error: Mismatch:" 101))
(if (equal? #f (lookup  t1    223   )   ) 'match (error "Error: Mismatch:" 102))
(if (equal? 4  (lookup  t1    110   )   ) 'match (error "Error: Mismatch:" 103))
(if (equal? #f  (lookup  t2    335   )   ) 'match (error "Error: Mismatch:" 104))
(if (equal? #f (lookup  t1    416   )   ) 'match (error "Error: Mismatch:" 105))
(if (equal? #t  (lookup  t1    360   )   ) 'match (error "Error: Mismatch:" 106))
(if (equal? 1  (lookup  t1    410   )   ) 'match (error "Error: Mismatch:" 107))
(if (equal? 3  (lookup  t2    361   )   ) 'match (error "Error: Mismatch:" 108))
(if (equal? #f (lookup  t2    354   )   ) 'match (error "Error: Mismatch:" 109))
(if (equal? #f (lookup  t1    329   )   ) 'match (error "Error: Mismatch:" 110))
(if (equal? list  (lookup  t1    409   )   ) 'match (error "Error: Mismatch:" 111))
(if (equal? '(romeo juliet)  (lookup  t1    438   )   ) 'match (error "Error: Mismatch:" 112))
(if (equal? #f (lookup  t1    300   )   ) 'match (error "Error: Mismatch:" 113))
(if (equal? 3.1416  (lookup  t2    130   )   ) 'match (error "Error: Mismatch:" 114))
(if (equal? 'fox  (lookup  t1    404   )   ) 'match (error "Error: Mismatch:" 115))
(if (equal? #f (lookup  t1    104   )   ) 'match (error "Error: Mismatch:" 116))
(if (equal? 6  (lookup  t2    280   )   ) 'match (error "Error: Mismatch:" 117))
(if (equal? '(a . b)  (lookup  t2    416   )   ) 'match (error "Error: Mismatch:" 118))
(if (equal? '(larry moe curly)  (lookup  t1    318   )   ) 'match (error "Error: Mismatch:" 119))
(if (equal? #f (lookup  t1    381   )   ) 'match (error "Error: Mismatch:" 120))
(if (equal? #f (lookup  t1    238   )   ) 'match (error "Error: Mismatch:" 121))
(if (equal? car  (lookup  t2    186   )   ) 'match (error "Error: Mismatch:" 122))
(if (equal? #f (lookup  t1    337   )   ) 'match (error "Error: Mismatch:" 123))
(if (equal? #f (lookup  t1    365   )   ) 'match (error "Error: Mismatch:" 124))
(if (equal? 2  (lookup  t1    435   )   ) 'match (error "Error: Mismatch:" 125))
(if (equal? #f (lookup  t2    393   )   ) 'match (error "Error: Mismatch:" 126))
(if (equal? 'eel  (lookup  t2    442   )   ) 'match (error "Error: Mismatch:" 127))
(if (equal? 'cat  (lookup  t1    205   )   ) 'match (error "Error: Mismatch:" 128))
(if (equal? '(one)  (lookup  t1    316   )   ) 'match (error "Error: Mismatch:" 129))
(if (equal? 'fox  (lookup  t2    107   )   ) 'match (error "Error: Mismatch:" 130))
(if (equal? #f (lookup  t2    221   )   ) 'match (error "Error: Mismatch:" 131))
(if (equal? #f (lookup  t1    380   )   ) 'match (error "Error: Mismatch:" 132))
(if (equal? 3  (lookup  t2    342   )   ) 'match (error "Error: Mismatch:" 133))
(if (equal? 'cat  (lookup  t2    314   )   ) 'match (error "Error: Mismatch:" 134))
(if (equal? #t  (lookup  t2    297   )   ) 'match (error "Error: Mismatch:" 135))
(if (equal? #f (lookup  t2    435   )   ) 'match (error "Error: Mismatch:" 136))
(if (equal? #f (lookup  t2    306   )   ) 'match (error "Error: Mismatch:" 137))
(if (equal? '()  (lookup  t2    406   )   ) 'match (error "Error: Mismatch:" 138))
(if (equal? 3  (lookup  t2    342   )   ) 'match (error "Error: Mismatch:" 139))
(if (equal? '(one)  (lookup  t1    201   )   ) 'match (error "Error: Mismatch:" 140))
(if (equal? #f (lookup  t1    292   )   ) 'match (error "Error: Mismatch:" 141))
(if (equal? #f (lookup  t1    175   )   ) 'match (error "Error: Mismatch:" 142))
(if (equal? 1.4142  (lookup  t1    122   )   ) 'match (error "Error: Mismatch:" 143))
(if (equal? cdr  (lookup  t1    280   )   ) 'match (error "Error: Mismatch:" 144))
(if (equal? 'pig  (lookup  t2    211   )   ) 'match (error "Error: Mismatch:" 145))
(if (equal? #f (lookup  t1    444   )   ) 'match (error "Error: Mismatch:" 146))
(if (equal? #f (lookup  t2    156   )   ) 'match (error "Error: Mismatch:" 147))
(if (equal? #f (lookup  t2    360   )   ) 'match (error "Error: Mismatch:" 148))
(if (equal? 'jay  (lookup  t2    274   )   ) 'match (error "Error: Mismatch:" 149))
(if (equal? 'fox  (lookup  t1    393   )   ) 'match (error "Error: Mismatch:" 150))
(if (equal? #f (lookup  t2    357   )   ) 'match (error "Error: Mismatch:" 151))
(if (equal? #f (lookup  t1    195   )   ) 'match (error "Error: Mismatch:" 152))
(if (equal? #f (lookup  t1    260   )   ) 'match (error "Error: Mismatch:" 153))
(if (equal? 'dog  (lookup  t2    265   )   ) 'match (error "Error: Mismatch:" 154))
(if (equal? #f (lookup  t2    118   )   ) 'match (error "Error: Mismatch:" 155))
(if (equal? "cord"  (lookup  t2    216   )   ) 'match (error "Error: Mismatch:" 156))
(if (equal? #f (lookup  t1    215   )   ) 'match (error "Error: Mismatch:" 157))
(if (equal? #f (lookup  t1    292   )   ) 'match (error "Error: Mismatch:" 158))
(if (equal? #f (lookup  t2    200   )   ) 'match (error "Error: Mismatch:" 159))
(if (equal? '(romeo juliet)  (lookup  t2    330   )   ) 'match (error "Error: Mismatch:" 160))
(if (equal? #f (lookup  t1    143   )   ) 'match (error "Error: Mismatch:" 161))
(if (equal? #f (lookup  t2    129   )   ) 'match (error "Error: Mismatch:" 162))
(if (equal? #f (lookup  t2    313   )   ) 'match (error "Error: Mismatch:" 163))
(if (equal? '(1 . 2)  (lookup  t2    113   )   ) 'match (error "Error: Mismatch:" 164))
(if (equal? assoc  (lookup  t1    216   )   ) 'match (error "Error: Mismatch:" 165))
(if (equal? #f (lookup  t2    318   )   ) 'match (error "Error: Mismatch:" 166))
(if (equal? 'pig  (lookup  t2    244   )   ) 'match (error "Error: Mismatch:" 167))
(if (equal? #f (lookup  t2    387   )   ) 'match (error "Error: Mismatch:" 168))
(if (equal? 2.2361  (lookup  t2    108   )   ) 'match (error "Error: Mismatch:" 169))
(if (equal? "rope"  (lookup  t2    194   )   ) 'match (error "Error: Mismatch:" 170))
(if (equal? #f (lookup  t1    108   )   ) 'match (error "Error: Mismatch:" 171))
(if (equal? 1.4142  (lookup  t1    137   )   ) 'match (error "Error: Mismatch:" 172))
(if (equal? car  (lookup  t1    369   )   ) 'match (error "Error: Mismatch:" 173))
(if (equal? 5  (lookup  t1    207   )   ) 'match (error "Error: Mismatch:" 174))
(if (equal? 'cow  (lookup  t1    386   )   ) 'match (error "Error: Mismatch:" 175))
(if (equal? #f (lookup  t2    154   )   ) 'match (error "Error: Mismatch:" 176))
(if (equal? #f (lookup  t2    339   )   ) 'match (error "Error: Mismatch:" 177))
(if (equal? 1.4142  (lookup  t1    390   )   ) 'match (error "Error: Mismatch:" 178))
(if (equal? #f (lookup  t1    195   )   ) 'match (error "Error: Mismatch:" 179))
(if (equal? 3.1416  (lookup  t2    175   )   ) 'match (error "Error: Mismatch:" 180))
(if (equal? #f (lookup  t1    413   )   ) 'match (error "Error: Mismatch:" 181))
(if (equal? #f (lookup  t1    154   )   ) 'match (error "Error: Mismatch:" 182))
(if (equal? 'dog  (lookup  t2    394   )   ) 'match (error "Error: Mismatch:" 183))
(if (equal? 1.4142  (lookup  t1    335   )   ) 'match (error "Error: Mismatch:" 184))
(if (equal? #f (lookup  t2    375   )   ) 'match (error "Error: Mismatch:" 185))
(if (equal? "rope"  (lookup  t2    194   )   ) 'match (error "Error: Mismatch:" 186))
(if (equal? "rope"  (lookup  t2    402   )   ) 'match (error "Error: Mismatch:" 187))
(if (equal? 1.618  (lookup  t1    417   )   ) 'match (error "Error: Mismatch:" 188))
(if (equal? #f (lookup  t2    140   )   ) 'match (error "Error: Mismatch:" 189))
(if (equal? car  (lookup  t1    317   )   ) 'match (error "Error: Mismatch:" 190))
(if (equal? "cord"  (lookup  t2    372   )   ) 'match (error "Error: Mismatch:" 191))
(if (equal? 5  (lookup  t2    389   )   ) 'match (error "Error: Mismatch:" 192))
(if (equal? '(1 . 2)  (lookup  t1    220   )   ) 'match (error "Error: Mismatch:" 193))
(if (equal? 'owl  (lookup  t2    404   )   ) 'match (error "Error: Mismatch:" 194))
(if (equal? '(1 . 2)  (lookup  t1    446   )   ) 'match (error "Error: Mismatch:" 195))
(if (equal? '(larry moe curly)  (lookup  t2    302   )   ) 'match (error "Error: Mismatch:" 196))
(if (equal? "rope"  (lookup  t1    296   )   ) 'match (error "Error: Mismatch:" 197))
(if (equal? #f (lookup  t1    143   )   ) 'match (error "Error: Mismatch:" 198))
(if (equal? '(larry moe curly)  (lookup  t2    277   )   ) 'match (error "Error: Mismatch:" 199))
(if (equal? #f (lookup  t2    320   )   ) 'match (error "Error: Mismatch:" 200))
(if (equal? #f (lookup  t1    387   )   ) 'match (error "Error: Mismatch:" 201))
(if (equal? '(one)  (lookup  t1    376   )   ) 'match (error "Error: Mismatch:" 202))
(if (equal? '(one)  (lookup  t2    151   )   ) 'match (error "Error: Mismatch:" 203))
(if (equal? #f (lookup  t1    275   )   ) 'match (error "Error: Mismatch:" 204))
(if (equal? list  (lookup  t2    441   )   ) 'match (error "Error: Mismatch:" 205))
(if (equal? assoc  (lookup  t2    271   )   ) 'match (error "Error: Mismatch:" 206))
(if (equal? #f (lookup  t1    436   )   ) 'match (error "Error: Mismatch:" 207))
(if (equal? 4  (lookup  t1    178   )   ) 'match (error "Error: Mismatch:" 208))
(if (equal? '(romeo juliet)  (lookup  t1    438   )   ) 'match (error "Error: Mismatch:" 209))
(if (equal? "cord"  (lookup  t1    262   )   ) 'match (error "Error: Mismatch:" 210))
(if (equal? 'cow  (lookup  t1    152   )   ) 'match (error "Error: Mismatch:" 211))
(if (equal? 4  (lookup  t2    241   )   ) 'match (error "Error: Mismatch:" 212))
(if (equal? "cord"  (lookup  t2    329   )   ) 'match (error "Error: Mismatch:" 213))
(if (equal? '(larry moe curly)  (lookup  t2    397   )   ) 'match (error "Error: Mismatch:" 214))
(if (equal? 4  (lookup  t2    260   )   ) 'match (error "Error: Mismatch:" 215))
(if (equal? cdr  (lookup  t1    169   )   ) 'match (error "Error: Mismatch:" 216))
(if (equal? "rope"  (lookup  t1    333   )   ) 'match (error "Error: Mismatch:" 217))
(if (equal? #f (lookup  t1    342   )   ) 'match (error "Error: Mismatch:" 218))
(if (equal? "cord"  (lookup  t1    105   )   ) 'match (error "Error: Mismatch:" 219))
(if (equal? #f (lookup  t2    158   )   ) 'match (error "Error: Mismatch:" 220))
(if (equal? list  (lookup  t1    409   )   ) 'match (error "Error: Mismatch:" 221))
(if (equal? assoc  (lookup  t1    253   )   ) 'match (error "Error: Mismatch:" 222))
(if (equal? #f (lookup  t1    208   )   ) 'match (error "Error: Mismatch:" 223))
(if (equal? 'dog  (lookup  t2    293   )   ) 'match (error "Error: Mismatch:" 224))
(if (equal? 'cow  (lookup  t2    242   )   ) 'match (error "Error: Mismatch:" 225))
(if (equal? #f (lookup  t2    261   )   ) 'match (error "Error: Mismatch:" 226))
(if (equal? 'owl  (lookup  t2    400   )   ) 'match (error "Error: Mismatch:" 227))
(if (equal? #f (lookup  t2    340   )   ) 'match (error "Error: Mismatch:" 228))
(if (equal? 2.2361  (lookup  t1    174   )   ) 'match (error "Error: Mismatch:" 229))
(if (equal? 'jay  (lookup  t1    445   )   ) 'match (error "Error: Mismatch:" 230))
(if (equal? 'dog  (lookup  t2    265   )   ) 'match (error "Error: Mismatch:" 231))
(if (equal? #f (lookup  t1    291   )   ) 'match (error "Error: Mismatch:" 232))
(if (equal? 3  (lookup  t2    384   )   ) 'match (error "Error: Mismatch:" 233))
(if (equal? #f (lookup  t1    319   )   ) 'match (error "Error: Mismatch:" 234))
(if (equal? car  (lookup  t1    167   )   ) 'match (error "Error: Mismatch:" 235))
(if (equal? #t  (lookup  t1    128   )   ) 'match (error "Error: Mismatch:" 236))
(if (equal? #f (lookup  t1    278   )   ) 'match (error "Error: Mismatch:" 237))
(if (equal? '(1 . 2)  (lookup  t1    298   )   ) 'match (error "Error: Mismatch:" 238))
(if (equal? #f (lookup  t2    267   )   ) 'match (error "Error: Mismatch:" 239))
(if (equal? '(1 . 2)  (lookup  t1    344   )   ) 'match (error "Error: Mismatch:" 240))
(if (equal? #f (lookup  t2    296   )   ) 'match (error "Error: Mismatch:" 241))
(if (equal? #f (lookup  t2    318   )   ) 'match (error "Error: Mismatch:" 242))
(if (equal? #f (lookup  t2    153   )   ) 'match (error "Error: Mismatch:" 243))
(if (equal? #f (lookup  t2    193   )   ) 'match (error "Error: Mismatch:" 244))
(if (equal? #f (lookup  t2    135   )   ) 'match (error "Error: Mismatch:" 245))
(if (equal? "twine"  (lookup  t2    337   )   ) 'match (error "Error: Mismatch:" 246))
(if (equal? #f (lookup  t2    147   )   ) 'match (error "Error: Mismatch:" 247))
(if (equal? '(one)  (lookup  t2    390   )   ) 'match (error "Error: Mismatch:" 248))
(if (equal? '(romeo juliet)  (lookup  t2    330   )   ) 'match (error "Error: Mismatch:" 249))
(if (equal? 3.1416  (lookup  t1    401   )   ) 'match (error "Error: Mismatch:" 250))
(if (equal? 3.1416  (lookup  t2    175   )   ) 'match (error "Error: Mismatch:" 251))
(if (equal? #f (lookup  t1    154   )   ) 'match (error "Error: Mismatch:" 252))
(if (equal? 2  (lookup  t1    308   )   ) 'match (error "Error: Mismatch:" 253))
(if (equal? '(larry moe curly)  (lookup  t2    277   )   ) 'match (error "Error: Mismatch:" 254))
(if (equal? 1.618  (lookup  t2    276   )   ) 'match (error "Error: Mismatch:" 255))
(if (equal? 3.1416  (lookup  t1    400   )   ) 'match (error "Error: Mismatch:" 256))
(if (equal? 2.2361  (lookup  t2    108   )   ) 'match (error "Error: Mismatch:" 257))
(if (equal? 7  (lookup  t2    436   )   ) 'match (error "Error: Mismatch:" 258))
(if (equal? 'pig  (lookup  t1    141   )   ) 'match (error "Error: Mismatch:" 259))
(if (equal? 5  (lookup  t2    424   )   ) 'match (error "Error: Mismatch:" 260))
(if (equal? 7  (lookup  t2    436   )   ) 'match (error "Error: Mismatch:" 261))
(if (equal? #f (lookup  t2    443   )   ) 'match (error "Error: Mismatch:" 262))
(if (equal? assoc  (lookup  t1    171   )   ) 'match (error "Error: Mismatch:" 263))
(if (equal? cdr  (lookup  t1    194   )   ) 'match (error "Error: Mismatch:" 264))
(if (equal? 3  (lookup  t2    382   )   ) 'match (error "Error: Mismatch:" 265))
(if (equal? #f (lookup  t2    399   )   ) 'match (error "Error: Mismatch:" 266))
(if (equal? #f (lookup  t1    263   )   ) 'match (error "Error: Mismatch:" 267))
(if (equal? 2  (lookup  t1    264   )   ) 'match (error "Error: Mismatch:" 268))
(if (equal? #f (lookup  t2    351   )   ) 'match (error "Error: Mismatch:" 269))
(if (equal? #f (lookup  t2    286   )   ) 'match (error "Error: Mismatch:" 270))
(if (equal? "rope"  (lookup  t1    265   )   ) 'match (error "Error: Mismatch:" 271))
(if (equal? assoc  (lookup  t1    199   )   ) 'match (error "Error: Mismatch:" 272))
(if (equal? 3.1416  (lookup  t1    180   )   ) 'match (error "Error: Mismatch:" 273))
(if (equal? #f  (lookup  t2    335   )   ) 'match (error "Error: Mismatch:" 274))
(if (equal? '(a . b)  (lookup  t2    416   )   ) 'match (error "Error: Mismatch:" 275))
(if (equal? #f (lookup  t1    405   )   ) 'match (error "Error: Mismatch:" 276))
(if (equal? #f (lookup  t1    330   )   ) 'match (error "Error: Mismatch:" 277))
(if (equal? #f (lookup  t2    278   )   ) 'match (error "Error: Mismatch:" 278))
(if (equal? #f (lookup  t2    229   )   ) 'match (error "Error: Mismatch:" 279))
(if (equal? "twine"  (lookup  t2    419   )   ) 'match (error "Error: Mismatch:" 280))
(if (equal? #f (lookup  t1    371   )   ) 'match (error "Error: Mismatch:" 281))
(if (equal? 'jay  (lookup  t1    257   )   ) 'match (error "Error: Mismatch:" 282))
(if (equal? assoc  (lookup  t1    199   )   ) 'match (error "Error: Mismatch:" 283))
(if (equal? #f (lookup  t2    112   )   ) 'match (error "Error: Mismatch:" 284))
(if (equal? 1.618  (lookup  t1    406   )   ) 'match (error "Error: Mismatch:" 285))
(if (equal? "rope"  (lookup  t2    119   )   ) 'match (error "Error: Mismatch:" 286))
(if (equal? #f (lookup  t1    398   )   ) 'match (error "Error: Mismatch:" 287))
(if (equal? "cord"  (lookup  t1    105   )   ) 'match (error "Error: Mismatch:" 288))
(if (equal? #f  (lookup  t2    335   )   ) 'match (error "Error: Mismatch:" 289))
(if (equal? #f (lookup  t2    334   )   ) 'match (error "Error: Mismatch:" 290))
(if (equal? #f (lookup  t2    307   )   ) 'match (error "Error: Mismatch:" 291))
(if (equal? list  (lookup  t1    437   )   ) 'match (error "Error: Mismatch:" 292))
(if (equal? 1.618  (lookup  t1    412   )   ) 'match (error "Error: Mismatch:" 293))
(if (equal? list  (lookup  t1    437   )   ) 'match (error "Error: Mismatch:" 294))
(if (equal? #f (lookup  t1    338   )   ) 'match (error "Error: Mismatch:" 295))
(if (equal? #f (lookup  t1    391   )   ) 'match (error "Error: Mismatch:" 296))
(if (equal? 1.7321  (lookup  t1    297   )   ) 'match (error "Error: Mismatch:" 297))
(if (equal? '(1 . 2)  (lookup  t1    399   )   ) 'match (error "Error: Mismatch:" 298))
(if (equal? 1.7321  (lookup  t1    142   )   ) 'match (error "Error: Mismatch:" 299))
(if (equal? cdr  (lookup  t2    379   )   ) 'match (error "Error: Mismatch:" 300))
(if (equal? 1.4142  (lookup  t1    236   )   ) 'match (error "Error: Mismatch:" 301))
(if (equal? #f (lookup  t1    147   )   ) 'match (error "Error: Mismatch:" 302))
(if (equal? car  (lookup  t2    226   )   ) 'match (error "Error: Mismatch:" 303))
(if (equal? #f (lookup  t2    115   )   ) 'match (error "Error: Mismatch:" 304))
(if (equal? 'owl  (lookup  t2    400   )   ) 'match (error "Error: Mismatch:" 305))
(if (equal? 1.7321  (lookup  t1    447   )   ) 'match (error "Error: Mismatch:" 306))
(if (equal? 3  (lookup  t2    148   )   ) 'match (error "Error: Mismatch:" 307))
(if (equal? 'pig  (lookup  t1    139   )   ) 'match (error "Error: Mismatch:" 308))
(if (equal? #f (lookup  t2    255   )   ) 'match (error "Error: Mismatch:" 309))
(if (equal? #f (lookup  t2    344   )   ) 'match (error "Error: Mismatch:" 310))
(if (equal? #f (lookup  t1    234   )   ) 'match (error "Error: Mismatch:" 311))
(if (equal? #f (lookup  t1    258   )   ) 'match (error "Error: Mismatch:" 312))
(if (equal? '(1 . 2)  (lookup  t1    220   )   ) 'match (error "Error: Mismatch:" 313))
(if (equal? 4  (lookup  t1    178   )   ) 'match (error "Error: Mismatch:" 314))
(if (equal? #f (lookup  t2    123   )   ) 'match (error "Error: Mismatch:" 315))
(if (equal? #f (lookup  t1    202   )   ) 'match (error "Error: Mismatch:" 316))
(if (equal? 3.1416  (lookup  t2    130   )   ) 'match (error "Error: Mismatch:" 317))
(if (equal? 'dog  (lookup  t2    293   )   ) 'match (error "Error: Mismatch:" 318))
(if (equal? '(1 . 2)  (lookup  t2    113   )   ) 'match (error "Error: Mismatch:" 319))
(if (equal? 'pig  (lookup  t2    211   )   ) 'match (error "Error: Mismatch:" 320))
(if (equal? assoc  (lookup  t2    189   )   ) 'match (error "Error: Mismatch:" 321))
(if (equal? car  (lookup  t1    283   )   ) 'match (error "Error: Mismatch:" 322))
(if (equal? cdr  (lookup  t1    280   )   ) 'match (error "Error: Mismatch:" 323))
(if (equal? 3  (lookup  t2    362   )   ) 'match (error "Error: Mismatch:" 324))
(if (equal? "rope"  (lookup  t1    267   )   ) 'match (error "Error: Mismatch:" 325))
(if (equal? '(1 . 2)  (lookup  t1    448   )   ) 'match (error "Error: Mismatch:" 326))
(if (equal? "twine"  (lookup  t2    299   )   ) 'match (error "Error: Mismatch:" 327))
(if (equal? "twine"  (lookup  t2    285   )   ) 'match (error "Error: Mismatch:" 328))
(if (equal? #f (lookup  t2    235   )   ) 'match (error "Error: Mismatch:" 329))
(if (equal? #f (lookup  t2    258   )   ) 'match (error "Error: Mismatch:" 330))
(if (equal? 1.4142  (lookup  t1    345   )   ) 'match (error "Error: Mismatch:" 331))
(if (equal? #f (lookup  t1    219   )   ) 'match (error "Error: Mismatch:" 332))
(if (equal? #f (lookup  t1    181   )   ) 'match (error "Error: Mismatch:" 333))
(if (equal? 2.2361  (lookup  t1    174   )   ) 'match (error "Error: Mismatch:" 334))
(if (equal? #f (lookup  t1    284   )   ) 'match (error "Error: Mismatch:" 335))
(if (equal? #f (lookup  t1    177   )   ) 'match (error "Error: Mismatch:" 336))
(if (equal? #t  (lookup  t2    414   )   ) 'match (error "Error: Mismatch:" 337))
(if (equal? #f (lookup  t2    209   )   ) 'match (error "Error: Mismatch:" 338))
(if (equal? "rope"  (lookup  t2    402   )   ) 'match (error "Error: Mismatch:" 339))
(if (equal? #f (lookup  t2    412   )   ) 'match (error "Error: Mismatch:" 340))
(if (equal? 2.2361  (lookup  t1    361   )   ) 'match (error "Error: Mismatch:" 341))
(if (equal? #f (lookup  t1    338   )   ) 'match (error "Error: Mismatch:" 342))
(if (equal? 6  (lookup  t1    126   )   ) 'match (error "Error: Mismatch:" 343))
(if (equal? "twine"  (lookup  t2    299   )   ) 'match (error "Error: Mismatch:" 344))
(if (equal? #f (lookup  t1    222   )   ) 'match (error "Error: Mismatch:" 345))
(if (equal? 'pig  (lookup  t2    262   )   ) 'match (error "Error: Mismatch:" 346))
(if (equal? 1.618  (lookup  t2    358   )   ) 'match (error "Error: Mismatch:" 347))
(if (equal? #f (lookup  t1    353   )   ) 'match (error "Error: Mismatch:" 348))
(if (equal? '(larry moe curly)  (lookup  t1    318   )   ) 'match (error "Error: Mismatch:" 349))
(if (equal? 7  (lookup  t2    185   )   ) 'match (error "Error: Mismatch:" 350))
(if (equal? #f (lookup  t1    402   )   ) 'match (error "Error: Mismatch:" 351))
(if (equal? #f (lookup  t1    365   )   ) 'match (error "Error: Mismatch:" 352))
(if (equal? #f (lookup  t2    269   )   ) 'match (error "Error: Mismatch:" 353))
(if (equal? list  (lookup  t2    441   )   ) 'match (error "Error: Mismatch:" 354))
(if (equal? 1.4142  (lookup  t1    137   )   ) 'match (error "Error: Mismatch:" 355))
(if (equal? car  (lookup  t2    392   )   ) 'match (error "Error: Mismatch:" 356))
(if (equal? #f (lookup  t1    218   )   ) 'match (error "Error: Mismatch:" 357))
(if (equal? 'pig  (lookup  t2    281   )   ) 'match (error "Error: Mismatch:" 358))
(if (equal? #f (lookup  t1    367   )   ) 'match (error "Error: Mismatch:" 359))
(if (equal? 'cat  (lookup  t2    314   )   ) 'match (error "Error: Mismatch:" 360))
(if (equal? 1.7321  (lookup  t1    231   )   ) 'match (error "Error: Mismatch:" 361))
(if (equal? '(romeo juliet)  (lookup  t1    388   )   ) 'match (error "Error: Mismatch:" 362))
(if (equal? #f (lookup  t2    278   )   ) 'match (error "Error: Mismatch:" 363))
(if (equal? #f (lookup  t2    438   )   ) 'match (error "Error: Mismatch:" 364))
(if (equal? #f (lookup  t1    243   )   ) 'match (error "Error: Mismatch:" 365))
(if (equal? #f (lookup  t1    402   )   ) 'match (error "Error: Mismatch:" 366))
(if (equal? 4  (lookup  t2    213   )   ) 'match (error "Error: Mismatch:" 367))
(if (equal? 'dog  (lookup  t2    284   )   ) 'match (error "Error: Mismatch:" 368))
(if (equal? 'dog  (lookup  t2    198   )   ) 'match (error "Error: Mismatch:" 369))
(if (equal? #f (lookup  t2    110   )   ) 'match (error "Error: Mismatch:" 370))
(if (equal? '(a . b)  (lookup  t1    428   )   ) 'match (error "Error: Mismatch:" 371))
(if (equal? #f (lookup  t1    242   )   ) 'match (error "Error: Mismatch:" 372))
(if (equal? cdr  (lookup  t2    128   )   ) 'match (error "Error: Mismatch:" 373))
(if (equal? 2  (lookup  t2    191   )   ) 'match (error "Error: Mismatch:" 374))
(if (equal? '()  (lookup  t2    207   )   ) 'match (error "Error: Mismatch:" 375))
(if (equal? 1.4142  (lookup  t2    447   )   ) 'match (error "Error: Mismatch:" 376))
(if (equal? #f  (lookup  t2    170   )   ) 'match (error "Error: Mismatch:" 377))
(if (equal? 'pig  (lookup  t2    244   )   ) 'match (error "Error: Mismatch:" 378))
(if (equal? 1.7321  (lookup  t2    304   )   ) 'match (error "Error: Mismatch:" 379))
(if (equal? 2  (lookup  t2    233   )   ) 'match (error "Error: Mismatch:" 380))
(if (equal? #f (lookup  t1    270   )   ) 'match (error "Error: Mismatch:" 381))
(if (equal? #f (lookup  t2    438   )   ) 'match (error "Error: Mismatch:" 382))
(if (equal? '(one)  (lookup  t1    189   )   ) 'match (error "Error: Mismatch:" 383))
(if (equal? #f (lookup  t2    343   )   ) 'match (error "Error: Mismatch:" 384))
(if (equal? #f (lookup  t1    123   )   ) 'match (error "Error: Mismatch:" 385))
(if (equal? 2  (lookup  t2    191   )   ) 'match (error "Error: Mismatch:" 386))
(if (equal? #f (lookup  t1    324   )   ) 'match (error "Error: Mismatch:" 387))
(if (equal? '(a . b)  (lookup  t2    283   )   ) 'match (error "Error: Mismatch:" 388))
(if (equal? list  (lookup  t1    135   )   ) 'match (error "Error: Mismatch:" 389))
(if (equal? 1.4142  (lookup  t1    375   )   ) 'match (error "Error: Mismatch:" 390))
(if (equal? 'cat  (lookup  t1    389   )   ) 'match (error "Error: Mismatch:" 391))
(if (equal? #f (lookup  t2    286   )   ) 'match (error "Error: Mismatch:" 392))
(if (equal? #f (lookup  t1    398   )   ) 'match (error "Error: Mismatch:" 393))
(if (equal? car  (lookup  t1    317   )   ) 'match (error "Error: Mismatch:" 394))
(if (equal? cdr  (lookup  t2    232   )   ) 'match (error "Error: Mismatch:" 395))
(if (equal? #f (lookup  t1    241   )   ) 'match (error "Error: Mismatch:" 396))
(if (equal? "rope"  (lookup  t2    398   )   ) 'match (error "Error: Mismatch:" 397))
(if (equal? 'cat  (lookup  t1    205   )   ) 'match (error "Error: Mismatch:" 398))
(if (equal? '(romeo juliet)  (lookup  t2    223   )   ) 'match (error "Error: Mismatch:" 399))
(if (equal? #f (lookup  t2    434   )   ) 'match (error "Error: Mismatch:" 400))